### ISSUE TITLE
TIF masks created when saving ROIS are upside down

### ISSUE THREAD

**Issue by ajkswamy** [grg2rsr/ILTIS#24]
I created a polygon ROI and saved it and ILTIS created a "..._mask.tif" file. When I open this file in ImageJ, it looks upside down compared to the ROI that I drew. @grg2rsr is this intentional?

**Comment by grg2rsr** [comment]
not really, but this bug is known. This should apply not only to masks, but to all .tifs. All iltis based coordinates are flipped in some relation to the way how fiji draws things, but I forgot exactly how. Since it's all relative, no result is affected by this.

**Comment by ajkswamy** [comment]
Yes, you are right. I think ILTIS assumes origin to be bottom left while fiji assumes top. Thanks!
